server:
  port:8080
spring:
  profiles:
    active: dev
  application:
    name: shop

mybatis:
  mapper-location: classpath:mapper/**/*.xml
  type-aliases-package: com.hzs.**.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"